baseURL: http://jiang.news/
languageCode: en-us
title: My New Hugo Site
theme: PaperMod
param: 

menu: 
  main: 
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 3