baseURL: http://jiang.news/
languageCode: en-us
title: Jiang.news
theme: PaperMod
params: 

  showBreadCrumbs: true
  showReadingTime: true
  showShareButtons: true
  showPostNavLinks: true

  ShareButtons: ["telegram"]

  homeInfoParams:
    enabled: true
    Title: Hi there wave
    Content: Can be Info, links, about...

  profileMode:
    enabled: true
    title: "<THIS IS Title>" # optional default will be site title
    subtitle: "Hi there, this is Jiang's self-reserved cropland."
    imageUrl: "XIAOZHOU/xiaozhou-1s.png" # optional
    imageTitle: "This is called XIAOZHOW, the icon of mine." # optional
    imageWidth: 240 # custom size
    imageHeight: 240 # custom size
    buttons:
      - name: Archive
        url: "/archives"
      - name: Github
        url: "https://github.com/jiangqucheng"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/jiangqucheng"
    - name: "bilibili"
      url: "https://space.bilibili.com/10861680"
    - name: "facebook"
      url: "https://www.facebook.com/qucheng.jiang"
    - name: "email"
      url: "mailto://jiangquchengpeter@hotmail.com"

menu: 
  main: 
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 3